### PR TITLE
Give users the opportunity to specify a domain at FMC instanciation, …

### PR DESCRIPTION
**Pull request by BaaptM**
…if no domain specified, fallback to Global

Iterate over all domain name and search for user input domain name (case insensitive)

PR on master branch, previous one (closed) was a mistake, sorry for that!

### CODE REVIEW

**Comment by daxm** [comment]
BaaptM:
  I have to admit that I'm not well versed in integrating people's pull requests.  That said, your code "looks" good to me.  However, I ask that you create a for your newly created Class and put it in the TestingUserScript.py before I merge your code.

If you'd like, I'd be willing to get on a call with you and we can discuss further development of fmcapi as well.  (As you may have noticed, I haven't developed on it for almost 1 year now.)  :-(

**Comment by BaaptM** [comment]
@daxm 
Test for PortObjectGroup added!

I'm currently in the middle of an ASA (FWSM in fact) to FTD migration project, found your code and it saves me a lot of time as I didn't have to rewrite the whole thing myself. I'm using it as a connector between my core code and the FMC API. 

I'm sure other people will find it useful too, so I decided to push some changes. I plan to add more code to fit the needs of my project and I could make more PR If you're interested. I'll be glad getting in touch for further talk!

**Comment by daxm** [comment]
Thank you!  I've merged in your code but haven't tested it yet.  (I don't have a lab FTD/FMC right now.)
However, once I get it tested I'll create a new version and release it on pypi!

**Comment by daxm** [comment]
Just thought I'd let you know that version 0.55.38 of the fmcapi is released (which has your changes!).

**Pull request merged**
